'use client'

import { useState, useEffect, useCallback, useMemo, type ReactNode } from 'react'
import dynamic from 'next/dynamic'
import Link from 'next/link'
import { createClient } from '@/lib/supabase-browser'
import Alert from '@/components/Alert'
import { createPhoneNumberHandler } from '@/lib/formatters'
import { createOrganization } from '@/app/actions/organization'
import { useOrganization } from '@/lib/OrganizationContext'
import { normalizeUsState, normalizeUsZip } from '@/lib/us-states'
import { DASHBOARD_PAGE_GUTTER } from '@/lib/dashboard-page-gutter'
import { Badge } from '@/components/ui/badge'
import { type PeriodKey, PERIOD_OPTIONS, periodRange } from '@/lib/dashboard-period'

// Import centralized types
import type { OrganizationInfo } from '@/types'

const AddressAutocomplete = dynamic(() => import('@/components/AddressAutocomplete'), {
  ssr: false,
  loading: () => <div className="h-11 w-full rounded-xl border border-gray-300 bg-gray-50" />
})

const preloadAddressAutocomplete = () => {
  ;(AddressAutocomplete as unknown as { preload?: () => void }).preload?.()
}

// Activity feed type
interface ActivityItem {
  id: string
  type: 'team' | 'invite' | 'organization' | 'subscription'
  action: string
  title: string
  subtitle?: string
  timestamp: string
  icon: string
}

const activitySkeleton = Array.from({ length: 3 }, (_, i) => (
  <div key={`activity-skeleton-${i}`} className="animate-pulse flex items-center space-x-4">
    <div className="w-10 h-10 bg-gray-200 rounded-full"></div>
    <div className="flex-1 space-y-2">
      <div className="h-4 bg-gray-200 rounded w-3/4"></div>
      <div className="h-3 bg-gray-200 rounded w-1/2"></div>
    </div>
  </div>
))

/** Soft sky dashboard — blue presence without heavy glow */
const DASHBOARD_SURFACE =
  'min-h-screen bg-gradient-to-b from-slate-50 via-sky-50/25 to-slate-50'

type Period = { now: number; prev: number }
const ZERO_PERIOD: Period = { now: 0, prev: 0 }

/** Up / down / flat delta pill comparing the current period to the previous one. */
function DeltaChip({ now, prev }: Period) {
  if (prev === 0 && now === 0) return <Badge variant="neutral">No change</Badge>
  if (prev === 0) return <Badge variant="success">↑ New</Badge>
  const pct = Math.round(((now - prev) / prev) * 100)
  if (pct === 0) return <Badge variant="neutral">→ 0%</Badge>
  return (
    <Badge variant={pct > 0 ? 'success' : 'danger'}>
      {pct > 0 ? '↑' : '↓'} {Math.abs(pct)}%
    </Badge>
  )
}

/** Flat KPI tile: label, big value, and a delta vs the previous period. */
function KpiCard({
  label,
  value,
  delta,
}: {
  label: string
  value: ReactNode
  delta: Period
}) {
  return (
    <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.04)] transition-shadow hover:shadow-[0_1px_3px_rgba(15,23,42,0.08)]">
      <h3 className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</h3>
      <p className="mt-2 text-3xl font-semibold tracking-tight text-slate-900 tabular-nums">{value}</p>
      <div className="mt-3 flex items-center gap-2">
        <DeltaChip now={delta.now} prev={delta.prev} />
        <span className="text-xs text-slate-400">vs previous period</span>
      </div>
    </div>
  )
}

export default function Dashboard() {
  const { currentOrganization: ctxOrganization, hasOrganization: ctxHasOrganization } = useOrganization()
  // Basic state
  const [hasOrganization, setHasOrganization] = useState<boolean | null>(null)
  const [organization, setOrganization] = useState<OrganizationInfo | null>(null)
  const [loading, setLoading] = useState(true)
  const [showForm, setShowForm] = useState(false)
  
  // Form state
  const [organizationName, setOrganizationName] = useState<string>('')
  const [organizationEmail, setOrganizationEmail] = useState<string>('')
  const [organizationPhone, setOrganizationPhone] = useState<string>('')
  const [organizationAddress, setOrganizationAddress] = useState<string>('')
  const [subdomainOverride, setSubdomainOverride] = useState<string>('')
  const autoGeneratedSubdomain = useMemo(() => {
    if (!organizationName) return ''

    return organizationName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
  }, [organizationName])
  const subdomain = subdomainOverride || autoGeneratedSubdomain
  const [organizationZip, setOrganizationZip] = useState('')
  const [organizationCity, setOrganizationCity] = useState('')
  const [organizationState, setOrganizationState] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  
  // Overview state
  const [teamMemberCount, setTeamMemberCount] = useState<number>(0)
  const [periodKey, setPeriodKey] = useState<PeriodKey>('30d')
  const [firstName, setFirstName] = useState<string>('')
  const [showUpgrade, setShowUpgrade] = useState<boolean>(false)
  const [kpis, setKpis] = useState<{ members: Period; invites: Period; updates: Period; billing: Period }>({
    members: ZERO_PERIOD,
    invites: ZERO_PERIOD,
    updates: ZERO_PERIOD,
    billing: ZERO_PERIOD,
  })
  
  // Activity feed state
  const [recentActivity, setRecentActivity] = useState<ActivityItem[]>([])
  const [activityLoading, setActivityLoading] = useState(false)
  const canInviteTeam = hasOrganization === true
  const platformHost = typeof window !== 'undefined' ? window.location.host : 'localhost:3000'
  const platformProtocol = typeof window !== 'undefined' ? window.location.protocol : 'http:'
  const tenantHost = organization?.subdomain ? `${organization.subdomain}.${platformHost}` : ''

  useEffect(() => {
    if (showForm) {
      preloadAddressAutocomplete()
    }
  }, [showForm])

  // Load recent activity - parallelized queries
  const loadRecentActivity = useCallback(async (organizationId: string) => {
    if (!organizationId) return;

    setActivityLoading(true);
    try {
      const supabase = createClient();
      
      // Fire all independent queries in parallel
      const [teamResult, invitesResult, organizationResult, subscriptionResult] = await Promise.all([
        supabase
          .from('team_members')
          .select('id, role, created_at, updated_at')
          .eq('organization_id', organizationId)
          .order('created_at', { ascending: false })
          .limit(5),
        supabase
          .from('organization_invites')
          .select('id, email, created_at, accepted_at')
          .eq('organization_id', organizationId)
          .order('created_at', { ascending: false })
          .limit(3),
        supabase
          .from('organizations')
          .select('name, updated_at')
          .eq('id', organizationId)
          .single(),
        supabase
          .from('organization_subscriptions')
          .select('subscription_status, updated_at, created_at')
          .eq('organization_id', organizationId)
          .maybeSingle(),
      ]);

      const activities: ActivityItem[] = [];
      
      if (teamResult.data) {
        teamResult.data.forEach((member) => {
          activities.push({
            id: `team-${member.id}`,
            type: 'team',
            action: 'joined',
            title: `Team member added (${member.role})`,
            subtitle: 'Workspace access granted',
            timestamp: member.created_at ?? member.updated_at ?? new Date().toISOString(),
            icon: '👥'
          });
        });
      }
      
      if (invitesResult.data) {
        invitesResult.data.forEach((invite) => {
          activities.push({
            id: `invite-${invite.id}`,
            type: 'invite',
            action: invite.accepted_at ? 'accepted' : 'sent',
            title: invite.accepted_at ? `Invite accepted by ${invite.email}` : `Invite sent to ${invite.email}`,
            subtitle: invite.accepted_at ? 'New teammate joined' : 'Pending invitation',
            timestamp: invite.accepted_at ?? invite.created_at ?? new Date().toISOString(),
            icon: '✉️'
          });
        });
      }
      
      // Process organization data
      if (organizationResult.data?.updated_at) {
        const timeDiff = new Date().getTime() - new Date(organizationResult.data.updated_at).getTime();
        if (timeDiff < 7 * 24 * 60 * 60 * 1000) {
          activities.push({
            id: `organization-${organizationId}`,
            type: 'organization',
            action: 'updated',
            title: 'Organization information updated',
            subtitle: 'Profile settings changed',
            timestamp: organizationResult.data.updated_at,
            icon: '🏢'
          });
        }
      }
      
      if (subscriptionResult.data) {
        const sub = subscriptionResult.data as { subscription_status?: string; updated_at?: string; created_at?: string }
        activities.push({
          id: `subscription-${organizationId}`,
          type: 'subscription',
          action: 'updated',
          title: `Subscription ${sub.subscription_status ?? 'updated'}`,
          subtitle: 'Billing status changed',
          timestamp: sub.updated_at ?? sub.created_at ?? new Date().toISOString(),
          icon: '💳'
        });
      }
      
      // Sort all activities by timestamp and take the 5 most recent
      const sortedActivities = activities
        .sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
        .slice(0, 5);
      
      setRecentActivity(sortedActivities);
    } catch (error) {
      console.error('Error loading activity feed:', error);
    } finally {
      setActivityLoading(false);
    }
  }, []);
  
  // Organization context + greeting name + plan (point-in-time, not period)
  useEffect(() => {
    async function loadOverview() {
      try {
        if (!ctxOrganization?.id) {
          setHasOrganization(ctxHasOrganization)
          setLoading(false)
          return
        }

        const supabase = createClient()
        setOrganization(ctxOrganization)
        setHasOrganization(true)

        const [{ data: userData }, teamCountResult, planResult] = await Promise.all([
          supabase.auth.getUser(),
          supabase
            .from('team_members')
            .select('id', { count: 'exact', head: true })
            .eq('organization_id', ctxOrganization.id),
          supabase
            .from('organization_subscriptions')
            .select('subscription_status, plan_name')
            .eq('organization_id', ctxOrganization.id)
            .maybeSingle(),
        ])

        setTeamMemberCount(teamCountResult.count ?? 0)

        // Greeting name: profile full_name -> auth metadata -> email prefix.
        const user = userData?.user
        let name = ''
        if (user) {
          const { data: profile } = await supabase
            .from('profiles')
            .select('full_name')
            .eq('id', user.id)
            .maybeSingle()
          const meta = (user.user_metadata ?? {}) as { full_name?: string; name?: string }
          name =
            (profile?.full_name as string | undefined) ||
            meta.full_name ||
            meta.name ||
            (user.email ? user.email.split('@')[0] : '')
        }
        setFirstName(name ? name.trim().split(/\s+/)[0] : '')

        const planStatus = (planResult.data as { subscription_status?: string } | null)?.subscription_status
        setShowUpgrade(!(planStatus === 'active' || planStatus === 'on_trial'))

        await loadRecentActivity(ctxOrganization.id)
      } catch (error) {
        console.error('Error in loadOverview:', error)
        setHasOrganization(false)
      } finally {
        setLoading(false)
      }
    }

    loadOverview()
  }, [ctxOrganization, ctxHasOrganization, loadRecentActivity])

  // Period KPIs with previous-period comparison (re-runs when the range changes)
  useEffect(() => {
    const organizationId = ctxOrganization?.id
    if (!organizationId) return
    let cancelled = false

    async function loadKpis(id: string) {
      try {
        const supabase = createClient()
        const { curStart, prevStart, prevEnd } = periodRange(periodKey)
        const prevStartISO = new Date(prevStart).toISOString()

        const [membersRes, invitesRes, orgRes, subRes] = await Promise.all([
          supabase.from('team_members').select('created_at').eq('organization_id', id).gte('created_at', prevStartISO),
          supabase.from('organization_invites').select('created_at').eq('organization_id', id).gte('created_at', prevStartISO),
          supabase.from('organizations').select('updated_at').eq('id', id).gte('updated_at', prevStartISO).maybeSingle(),
          supabase.from('subscription_events').select('created_at').eq('organization_id', id).gte('created_at', prevStartISO),
        ])

        const bucket = (rows: Array<{ created_at?: string | null }> | null): Period => {
          let nowCount = 0
          let prevCount = 0
          for (const row of rows ?? []) {
            if (!row.created_at) continue
            const t = new Date(row.created_at).getTime()
            if (t >= curStart) nowCount++
            else if (t >= prevStart && t < prevEnd) prevCount++
          }
          return { now: nowCount, prev: prevCount }
        }

        let updatesNow = 0
        let updatesPrev = 0
        const orgUpdatedAt = (orgRes.data as { updated_at?: string | null } | null)?.updated_at
        if (orgUpdatedAt) {
          const t = new Date(orgUpdatedAt).getTime()
          if (t >= curStart) updatesNow = 1
          else if (t >= prevStart && t < prevEnd) updatesPrev = 1
        }

        if (!cancelled) {
          setKpis({
            members: bucket(membersRes.data as Array<{ created_at?: string | null }> | null),
            invites: bucket(invitesRes.data as Array<{ created_at?: string | null }> | null),
            updates: { now: updatesNow, prev: updatesPrev },
            billing: bucket(subRes.data as Array<{ created_at?: string | null }> | null),
          })
        }
      } catch (error) {
        console.error('Error loading KPIs:', error)
      }
    }

    loadKpis(organizationId)
    return () => {
      cancelled = true
    }
  }, [ctxOrganization?.id, periodKey])

  const handleSubmitOrganization = async (e: React.FormEvent) => {
    e.preventDefault()
    
    // Don't submit if already submitting
    if (submitting) return
    
    try {
      setSubmitting(true)
      setErrorMessage(null)
      
      // Server-side validation
      if (organizationName.length === 0 || organizationName.length > 50) {
        throw new Error('Organization name must be between 1 and 50 characters')
      }
      
      if (!subdomain) {
        throw new Error('Subdomain is required')
      }
      
      // Basic validation for subdomain format
      const subdomainRegex = /^[a-z0-9-]+$/
      if (!subdomainRegex.test(subdomain.toLowerCase())) {
        throw new Error('Subdomain can only contain lowercase letters, numbers, and hyphens')
      }
      
      if (organizationAddress.length === 0 || organizationAddress.length > 100) {
        throw new Error('Organization address must be between 1 and 100 characters')
      }

      const normalizedZip = normalizeUsZip(organizationZip)
      if (normalizedZip.length !== 5) {
        throw new Error('Organization zip code must be 5 digits')
      }

      if (organizationCity.length === 0 || organizationCity.length > 50) {
        throw new Error('Organization city must be between 1 and 50 characters')
      }

      const normalizedState = normalizeUsState(organizationState)
      if (normalizedState.length !== 2) {
        throw new Error('Organization state must be 2 characters')
      }

      if (normalizedZip !== organizationZip) {
        setOrganizationZip(normalizedZip)
      }

      if (normalizedState !== organizationState) {
        setOrganizationState(normalizedState)
      }
      
      if (!organizationPhone) {
        throw new Error('Phone number is required')
      }
      
      if (organizationPhone.length > 16) {
        throw new Error('Organization phone number must not exceed 16 characters')
      }
      
      if (!organizationEmail) {
        throw new Error('Email address is required')
      }
      
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
      if (!emailRegex.test(organizationEmail)) {
        throw new Error('Please enter a valid email address')
      }
      
      // Create new organization using server action
      const formData = new FormData(e.currentTarget as HTMLFormElement)
      const result = await createOrganization(formData)

      if (!result.success) {
        throw new Error(result.error)
      }
      
      // Update state with new organization
      setOrganization(result.data as OrganizationInfo)
      setHasOrganization(true)
      // Notify layout/sidebar to refresh immediately without full page reload
      if (typeof window !== 'undefined') {
        window.dispatchEvent(
          new CustomEvent('organization:created', { detail: result.data as OrganizationInfo })
        )
      }
      
      // Reset form
      setOrganizationName('')
      setSubdomainOverride('')
      setOrganizationAddress('')
      setOrganizationZip('')
      setOrganizationCity('')
      setOrganizationState('')
      setOrganizationPhone('')
      setOrganizationEmail('')
      setShowForm(false)
      
    } catch (err) {
      setErrorMessage(err instanceof Error ? err.message : 'An unknown error occurred')
    } finally {
      setSubmitting(false)
    }
  }

  // Format relative time
  const formatRelativeTime = useCallback((timestamp: string) => {
    const now = new Date();
    const time = new Date(timestamp);
    const diffInSeconds = Math.floor((now.getTime() - time.getTime()) / 1000);
    
    if (diffInSeconds < 60) return 'Just now';
    if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)}m ago`;
    if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)}h ago`;
    if (diffInSeconds < 604800) return `${Math.floor(diffInSeconds / 86400)}d ago`;
    return time.toLocaleDateString();
  }, []);

  const greeting = (() => {
    const hour = new Date().getHours()
    return hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'
  })()

  if (loading) {
    return (
      <div className={DASHBOARD_SURFACE}>
        <div className="p-4 sm:p-6 lg:px-0 lg:py-8">
          <div className={DASHBOARD_PAGE_GUTTER}>
            <div className="animate-pulse space-y-6">
              <div className="h-8 bg-gradient-to-r from-gray-200 to-gray-300 rounded-lg w-1/3"></div>
              <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
                <div className="space-y-4">
                  <div className="h-6 bg-gradient-to-r from-gray-200 to-gray-300 rounded w-1/4"></div>
                  <div className="h-32 bg-gradient-to-r from-gray-200 to-gray-300 rounded-lg"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className={DASHBOARD_SURFACE}>
      {/* Overview header */}
      <header className="border-b border-slate-200/70 bg-white">
        <div className={`${DASHBOARD_PAGE_GUTTER} py-6 sm:py-8`}>
          {organization ? (
            <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
              <div className="min-w-0">
                <p className="text-xs font-medium uppercase tracking-[0.14em] text-slate-400">
                  {PERIOD_OPTIONS.find((o) => o.key === periodKey)?.label}
                </p>
                <h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
                  {greeting}{firstName ? `, ${firstName}` : ''}
                </h1>
                <p className="mt-1.5 text-sm text-slate-500">
                  <span className="font-medium text-slate-700">{organization.name}</span>
                  <span className="mx-2 text-slate-300">·</span>
                  {teamMemberCount} team {teamMemberCount === 1 ? 'member' : 'members'} in your workspace
                </p>
              </div>

              <div className="flex flex-wrap items-center gap-2 sm:gap-3">
                <select
                  value={periodKey}
                  onChange={(e) => setPeriodKey(e.target.value as PeriodKey)}
                  className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 shadow-sm transition-colors focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-200"
                  aria-label="Date range"
                >
                  {PERIOD_OPTIONS.map((o) => (
                    <option key={o.key} value={o.key}>
                      {o.label}
                    </option>
                  ))}
                </select>

                {showUpgrade ? (
                  <Link
                    href="/dashboard/manage-subscription"
                    className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-3.5 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-slate-800"
                  >
                    Upgrade to Pro
                    <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M7 17L17 7M9 7h8v8" />
                    </svg>
                  </Link>
                ) : null}

                {canInviteTeam ? (
                  <Link
                    href="/dashboard/team"
                    className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-sm font-semibold text-slate-800 shadow-sm transition-colors hover:bg-slate-50"
                  >
                    <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                    </svg>
                    Invite Team
                  </Link>
                ) : null}
              </div>
            </div>
          ) : (
            <h1 className="text-2xl font-semibold tracking-tight text-slate-900 sm:text-3xl">Dashboard</h1>
          )}
        </div>
      </header>
      
      {/* Content */}
      <main className={`${DASHBOARD_PAGE_GUTTER} py-6 sm:py-8`}>
        {hasOrganization === false ? (
          <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-xl border border-gray-200/50 p-6 sm:p-8">
            {!showForm ? (
              <div className="text-center">
                <div className="mx-auto w-20 h-20 bg-gradient-to-br from-blue-100 to-indigo-100 rounded-2xl flex items-center justify-center mb-6">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-10 h-10 text-indigo-600">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 21v-7.5a.75.75 0 01.75-.75h3a.75.75 0 01.75.75V21m-4.5 0H2.36m11.14 0H18m0 0h3.64m-1.39 0V9.349m-16.5 11.65V9.35m0 0a3.001 3.001 0 003.75-.615A2.993 2.993 0 009.75 9.75c.896 0 1.7-.393 2.25-1.016a2.993 2.993 0 002.25 1.016c.896 0 1.7-.393 2.25-1.016a3.001 3.001 0 003.75.614m-16.5 0a3.004 3.004 0 01-.621-4.72L4.318 3.44A1.5 1.5 0 015.378 3h13.243a1.5 1.5 0 011.06.44l1.19 1.189a3 3 0 01-.621 4.72m-13.5 8.65h3.75a.75.75 0 00.75-.75V13.5a.75.75 0 00-.75-.75H6.75a.75.75 0 00-.75.75v3.75c0 .415.336.75.75.75z" />
                  </svg>
                </div>
                <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-3">Welcome to My Company!</h2>
                <p className="text-gray-600 mb-8 text-lg max-w-md mx-auto">You need to create a organization to access all features of the platform.</p>
                <button
                  onClick={() => setShowForm(true)}
                  onMouseEnter={preloadAddressAutocomplete}
                  onFocus={preloadAddressAutocomplete}
                  className="inline-flex items-center justify-center px-8 py-4 bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-lg font-semibold rounded-xl shadow-lg hover:from-blue-700 hover:to-indigo-700 transition-all duration-200 transform hover:scale-105"
                >
                  Create Your Organization
                </button>
              </div>
            ) : (
              <div>
                <div className="flex justify-between items-center mb-8">
                  <div>
                    <h2 className="text-2xl sm:text-3xl font-bold text-gray-900">Create Your Organization</h2>
                    <p className="text-gray-600 mt-2">Set up your organization profile to get started</p>
                  </div>
                  <button
                    onClick={() => setShowForm(false)}
                    className="text-gray-400 hover:text-gray-600 transition-colors"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
                
                <form onSubmit={handleSubmitOrganization} className="space-y-6">
                  <div className="mb-2">
                    <div className="flex items-center justify-between text-xs text-gray-500">
                      <span>Setup progress</span>
                      <span>Step 1 of 1</span>
                    </div>
                    <div className="mt-2 h-2 w-full rounded-full bg-gray-100">
                      <div className="h-2 w-full rounded-full bg-gradient-to-r from-blue-600 to-indigo-600" />
                    </div>
                    <p className="mt-2 text-sm text-gray-600">
                      This takes ~2 minutes. You can edit details later.
                    </p>
                  </div>
                  <div>
                    <label htmlFor="organization-name" className="block text-sm font-medium text-gray-700">
                      Organization Name <span className="text-red-500">*</span>
                    </label>
                    <div className="mt-1">
                      <input
                        id="organization-name"
                        name="name"
                        type="text"
                        required
                        maxLength={50}
                        value={organizationName}
                        onChange={(e) => setOrganizationName(e.target.value)}
                        className="appearance-none block w-full px-4 py-3 border border-gray-300 rounded-xl shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
                        placeholder="e.g. Acme Auto Sales"
                      />
                      <p className="mt-1 text-xs text-gray-500">
                        {50 - organizationName.length} chars remaining
                      </p>
                    </div>
                  </div>

                  <div>
                    <label htmlFor="organization-subdomain" className="block text-sm font-medium text-gray-700">
                      Subdomain <span className="text-red-500">*</span>
                    </label>
                    <div className="mt-1 flex rounded-xl shadow-sm">
                      <input
                        id="organization-subdomain"
                        name="subdomain"
                        type="text"
                        required
                        value={subdomain}
                        onChange={(e) => setSubdomainOverride(e.target.value.toLowerCase())}
                        className="appearance-none flex-1 block w-full px-4 py-3 border border-r-0 border-gray-300 rounded-l-xl shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
                        placeholder="yourorganization"
                      />
                      <span className="inline-flex items-center px-4 py-3 rounded-r-xl border border-l-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">
                        .{platformHost}
                      </span>
                    </div>
                    <p className="mt-1 text-xs text-gray-500">
                      This will be your organization website URL. <span className="font-medium text-amber-600">This cannot be changed once set.</span> Initially populated from your organization name, but you can customize it.
                    </p>
                  </div>

                  <div>
                    <label htmlFor="organization-address" className="block text-sm font-medium text-gray-700">
                      Address <span className="text-red-500">*</span>
                    </label>
                    <div className="mt-1">
                      <AddressAutocomplete
                        name="address"
                        value={organizationAddress}
                        onChange={(address, addressParts) => {
                          setOrganizationAddress(address)
                          
                          // Autofill city, state, and zip if provided
                          if (addressParts) {
                            if (addressParts.city) setOrganizationCity(addressParts.city)
                            if (addressParts.state) setOrganizationState(normalizeUsState(addressParts.state))
                            if (addressParts.zip) setOrganizationZip(normalizeUsZip(addressParts.zip))
                          }
                        }}
                        placeholder="Enter organization address"
                      />
                      <p className="mt-1 text-xs text-gray-500">
                        Start typing to see address suggestions
                      </p>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div>
                      <label htmlFor="organization-zip" className="block text-sm font-medium text-gray-700">
                        Zip Code <span className="text-red-500">*</span>
                      </label>
                      <div className="mt-1">
                        <input
                          id="organization-zip"
                          name="zip"
                          type="text"
                          required
                          maxLength={5}
                          value={organizationZip}
                          onChange={(e) => setOrganizationZip(normalizeUsZip(e.target.value))}
                          className="appearance-none block w-full px-4 py-3 border border-gray-300 rounded-xl shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
                          placeholder="e.g. 12345"
                        />
                        <p className="mt-1 text-xs text-gray-500">
                          Maximum 5 digits
                        </p>
                      </div>
                    </div>

                    <div>
                      <label htmlFor="organization-city" className="block text-sm font-medium text-gray-700">
                        City <span className="text-red-500">*</span>
                      </label>
                      <div className="mt-1">
                        <input
                          id="organization-city"
                          name="city"
                          type="text"
                          required
                          maxLength={50}
                          value={organizationCity}
                          onChange={(e) => setOrganizationCity(e.target.value)}
                          className="appearance-none block w-full px-4 py-3 border border-gray-300 rounded-xl shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
                          placeholder="e.g. Anytown"
                        />
                      </div>
                    </div>

                    <div>
                      <label htmlFor="organization-state" className="block text-sm font-medium text-gray-700">
                        State <span className="text-red-500">*</span>
                      </label>
                      <div className="mt-1">
                        <input
                          id="organization-state"
                          name="state"
                          type="text"
                          required
                          maxLength={2}
                          value={organizationState}
                          onChange={(e) => setOrganizationState(normalizeUsState(e.target.value))}
                          className="appearance-none block w-full px-4 py-3 border border-gray-300 rounded-xl shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
                          placeholder="e.g. CA"
                        />
                      </div>
                    </div>
                  </div>

                  <div>
                    <label htmlFor="organization-phone" className="block text-sm font-medium text-gray-700">
                      Phone Number <span className="text-red-500">*</span>
                    </label>
                    <div className="mt-1">
                      <input
                        id="organization-phone"
                        name="phone"
                        type="tel"
                        required
                        maxLength={16}
                        value={organizationPhone}
                        onChange={createPhoneNumberHandler(setOrganizationPhone)}
                        className="appearance-none block w-full px-4 py-3 border border-gray-300 rounded-xl shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
                        placeholder="e.g. (555) 123-4567"
                      />
                    </div>
                  </div>
                  
                  <div>
                    <label htmlFor="organization-email" className="block text-sm font-medium text-gray-700">
                      Email Address <span className="text-red-500">*</span>
                    </label>
                    <div className="mt-1">
                      <input
                        id="organization-email"
                        name="email"
                        type="email"
                        required
                        value={organizationEmail}
                        onChange={(e) => setOrganizationEmail(e.target.value)}
                        className="appearance-none block w-full px-4 py-3 border border-gray-300 rounded-xl shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900"
                        placeholder="e.g. contact@yourorganization.com"
                      />
                    </div>
                  </div>

                  {errorMessage ? <Alert type="error" message={errorMessage} className="mb-4" /> : null}

                  <div className="flex flex-col sm:flex-row items-center justify-end space-y-3 sm:space-y-0 sm:space-x-3 pt-6">
                    <button
                      type="button"
                      onClick={() => setShowForm(false)}
                      className="w-full sm:w-auto inline-flex items-center justify-center px-6 py-3 border border-gray-300 shadow-sm text-sm font-medium rounded-xl text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      disabled={submitting}
                      className={`w-full sm:w-auto inline-flex items-center justify-center px-8 py-3 border border-transparent text-sm font-medium rounded-xl shadow-sm text-white bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-all duration-200 ${submitting ? 'opacity-70 cursor-not-allowed' : 'cursor-pointer'}`}
                    >
                      {submitting ? 'Creating...' : 'Create Organization'}
                    </button>
                  </div>
                </form>
              </div>
            )}
          </div>
        ) : (
          <>
            {/* Stats — top of page */}
            <div className="mb-6">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <KpiCard label="Team members" value={kpis.members.now} delta={kpis.members} />
                <KpiCard label="Invites sent" value={kpis.invites.now} delta={kpis.invites} />
                <KpiCard label="Org updates" value={kpis.updates.now} delta={kpis.updates} />
                <KpiCard label="Billing events" value={kpis.billing.now} delta={kpis.billing} />
              </div>
            </div>
            
            <div className="mb-8 grid grid-cols-1 gap-6 sm:gap-6 xl:grid-cols-3 xl:gap-8">
              {/* Main column: welcome + activity */}
              <div className="flex flex-col gap-4 xl:col-span-2">
                <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between sm:gap-4">
                  <div className="min-w-0">
                    <h2 className="text-xl font-semibold tracking-tight text-slate-900 sm:text-2xl">
                      Welcome back, {organization?.name || 'there'}
                    </h2>
                    <p className="mt-0.5 text-sm text-slate-600">
                      Here&apos;s what&apos;s happening with your organization!
                    </p>
                  </div>
                  <div className="shrink-0 sm:hidden">
                    <Link
                      href="/dashboard/team"
                      className="inline-flex w-full items-center justify-center rounded-xl bg-sky-600 px-4 py-2.5 text-sm font-semibold text-white shadow-[0_2px_8px_-2px_rgba(2,132,199,0.35)] transition-colors hover:bg-sky-700"
                    >
                      <svg className="mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                      </svg>
                      Invite Team
                    </Link>
                  </div>
                </div>

                <div className="rounded-2xl border border-sky-200/35 bg-white/95 p-6 shadow-[0_1px_2px_rgba(15,23,42,0.04),0_6px_20px_-10px_rgba(56,189,248,0.08)] sm:p-8">
                  <div className="mb-6 flex items-center justify-between">
                    <h3 className="text-xl font-semibold text-slate-900">Recent Activity</h3>
                    <div className="text-sm text-gray-500">Last 7 days</div>
                  </div>
                  
                  {activityLoading ? (
                    <div className="space-y-4">{activitySkeleton}</div>
                  ) : recentActivity.length > 0 ? (
                    <div className="space-y-4">
                      {recentActivity.map((activity) => (
                        <div
                          key={activity.id}
                          className="flex items-start space-x-4 rounded-xl p-3 transition-colors hover:bg-sky-50/60"
                          style={{ contentVisibility: 'auto', containIntrinsicSize: '0 80px' }}
                        >
                          <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-sky-100/80 text-lg">
                            {activity.icon}
                          </div>
                          <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium text-gray-900 truncate">
                              {activity.title}
                            </p>
                            {activity.subtitle ? (
                              <p className="text-sm text-gray-500 truncate">
                                {activity.subtitle}
                              </p>
                            ) : null}
                            <p className="text-xs text-gray-400 mt-1">
                              {formatRelativeTime(activity.timestamp)}
                            </p>
                          </div>
                          <div className="flex-shrink-0">
                            <span
                              className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${
                                activity.type === 'team'
                                  ? 'bg-sky-100/90 text-sky-800/85'
                                  : activity.type === 'invite'
                                    ? 'bg-emerald-50 text-emerald-800/85'
                                    : activity.type === 'organization'
                                      ? 'bg-violet-50 text-violet-800/85'
                                      : 'bg-amber-50 text-amber-900/80'
                              }`}
                            >
                              {activity.action}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="text-center py-8">
                      <div className="w-16 h-16 mx-auto mb-4 bg-gray-100 rounded-full flex items-center justify-center">
                        <svg className="w-8 h-8 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                        </svg>
                      </div>
                      <h4 className="text-lg font-medium text-gray-900 mb-2">No recent activity</h4>
                      <p className="text-gray-500">Activity will appear here as you manage your organization</p>
                    </div>
                  )}
                </div>
              </div>
              
              {/* Quick Actions Sidebar */}
              <div className="space-y-6">
                {/* Workspace */}
                <div className="rounded-2xl border border-sky-200/35 bg-white/95 p-6 shadow-[0_1px_2px_rgba(15,23,42,0.04),0_6px_20px_-10px_rgba(56,189,248,0.08)]">
                  <h3 className="mb-4 text-lg font-semibold text-slate-900">Your Workspace</h3>
                  
                  <div className="space-y-4">
                    <div>
                      <p className="text-sm text-gray-600 mb-2">Your organization subdomain:</p>
                      <a 
                        href={`${platformProtocol}//${tenantHost}`} 
                        target="_blank" 
                        rel="noopener noreferrer" 
                        className="break-all text-sm font-medium text-sky-700 underline decoration-sky-200 underline-offset-2 hover:text-sky-900"
                      >
                        {tenantHost}
                      </a>
                    </div>
                    
                    <div className="pt-2">
                      <Link 
                        href="/dashboard/profile" 
                        className="inline-flex w-full items-center justify-center rounded-xl border border-sky-200/60 bg-sky-50/80 px-4 py-3 text-sm font-medium text-sky-900 transition-colors hover:bg-sky-100/90 focus:outline-none focus:ring-2 focus:ring-sky-400/40 focus:ring-offset-2"
                      >
                        <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                        Manage Profile
                      </Link>
                    </div>
                  </div>
                </div>
                
                {/* Getting Started */}
                <div className="rounded-2xl border border-sky-200/35 bg-white/95 p-6 shadow-[0_1px_2px_rgba(15,23,42,0.04),0_6px_20px_-10px_rgba(56,189,248,0.08)]">
                  <h3 className="mb-6 text-lg font-semibold text-slate-900">Quick Actions</h3>
                  
                  <div className="space-y-4">
                    <Link 
                      href="/dashboard/team"
                      className="group flex items-center rounded-xl border border-sky-200/30 p-3 transition-colors hover:border-sky-200/60 hover:bg-sky-50/70"
                    >
                      <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg bg-sky-100/90 text-sky-700 group-hover:bg-sky-200/60">
                        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                        </svg>
                      </div>
                      <div className="ml-3 flex-1">
                        <h4 className="text-sm font-medium text-slate-900">Invite Team</h4>
                        <p className="text-xs text-slate-500">Add collaborators to your workspace</p>
                      </div>
                    </Link>
                    
                    <Link 
                      href="/dashboard/manage-subscription"
                      className="group flex items-center rounded-xl border border-sky-200/30 p-3 transition-colors hover:border-sky-200/60 hover:bg-sky-50/70"
                    >
                      <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg bg-sky-100/90 text-sky-700 group-hover:bg-sky-200/60">
                        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                        </svg>
                      </div>
                      <div className="ml-3 flex-1">
                        <h4 className="text-sm font-medium text-slate-900">Manage Billing</h4>
                        <p className="text-xs text-slate-500">Subscription and invoices</p>
                      </div>
                    </Link>
                    
                    <Link 
                      href="/dashboard/profile"
                      className="group flex items-center rounded-xl border border-sky-200/30 p-3 transition-colors hover:border-sky-200/60 hover:bg-sky-50/70"
                    >
                      <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg bg-sky-100/90 text-sky-700 group-hover:bg-sky-200/60">
                        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                      </div>
                      <div className="ml-3 flex-1">
                        <h4 className="text-sm font-medium text-slate-900">Profile Settings</h4>
                        <p className="text-xs text-slate-500">Update your account details</p>
                      </div>
                    </Link>
                  </div>
                </div>
                
                {/* Help Resources */}
                <div className="rounded-2xl border border-sky-200/35 bg-white/95 p-6 shadow-[0_1px_2px_rgba(15,23,42,0.04),0_6px_20px_-10px_rgba(56,189,248,0.08)]">
                  <h3 className="mb-4 text-lg font-semibold text-slate-900">Resources</h3>
                  
                  <div className="space-y-3">
                    <Link 
                      href="/features"
                      className="group flex items-center rounded-xl border border-sky-200/30 p-3 text-sm transition-colors hover:border-sky-200/55 hover:bg-sky-50/60"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="mr-3 h-4 w-4 text-sky-600">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
                      </svg>
                      <span className="font-medium text-slate-700 group-hover:text-sky-900">Feature guide</span>
                    </Link>
                    
                    <Link 
                      href="/contact" 
                      className="group flex items-center rounded-xl border border-sky-200/30 p-3 text-sm transition-colors hover:border-sky-200/55 hover:bg-sky-50/60"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="mr-3 h-4 w-4 text-sky-600">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
                      </svg>
                      <span className="font-medium text-slate-700 group-hover:text-sky-900">Contact Support</span>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </>
        )}
      </main>
    </div>
  )
} 
